"""empty message

Revision ID: 093d1aabbfcb
Revises: b1c4e6ff7ced
Create Date: 2023-10-24 21:53:02.637535

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '093d1aabbfcb'
down_revision: Union[str, None] = 'b1c4e6ff7ced'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('clients', 'sale_user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint('clients_sale_user_id_fkey', 'clients', type_='foreignkey')
    op.create_foreign_key(None, 'clients', 'users', ['sale_user_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint('contracts_client_id_fkey', 'contracts', type_='foreignkey')
    op.create_foreign_key(None, 'contracts', 'clients', ['client_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('events_support_user_id_fkey', 'events', type_='foreignkey')
    op.drop_constraint('events_contract_id_fkey', 'events', type_='foreignkey')
    op.create_foreign_key(None, 'events', 'contracts', ['contract_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'events', 'users', ['support_user_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint('users_role_id_fkey', 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'roles', ['role_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key('users_role_id_fkey', 'users', 'roles', ['role_id'], ['id'])
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.create_foreign_key('events_contract_id_fkey', 'events', 'contracts', ['contract_id'], ['id'])
    op.create_foreign_key('events_support_user_id_fkey', 'events', 'users', ['support_user_id'], ['id'])
    op.drop_constraint(None, 'contracts', type_='foreignkey')
    op.create_foreign_key('contracts_client_id_fkey', 'contracts', 'clients', ['client_id'], ['id'])
    op.drop_constraint(None, 'clients', type_='foreignkey')
    op.create_foreign_key('clients_sale_user_id_fkey', 'clients', 'users', ['sale_user_id'], ['id'])
    op.alter_column('clients', 'sale_user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
