"""empty message

Revision ID: 3362d341697e
Revises: 4271f7a7b015
Create Date: 2023-10-24 11:01:21.015999

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3362d341697e'
down_revision: Union[str, None] = '4271f7a7b015'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('events_client_id_fkey', 'events', type_='foreignkey')
    op.drop_column('events', 'client_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('client_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('events_client_id_fkey', 'events', 'clients', ['client_id'], ['id'])
    # ### end Alembic commands ###
