"""empty message

Revision ID: d1c060433836
Revises: e94c8a0b92d6
Create Date: 2023-10-23 23:54:39.805844

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1c060433836'
down_revision: Union[str, None] = 'e94c8a0b92d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('clients_commercial_user_id_fkey', 'clients', type_='foreignkey')
    op.alter_column('clients', 'commercial_user_id', new_column_name='sale_user_id')
    op.create_foreign_key(None, 'clients', 'users', ['sale_user_id'], ['id'])
    op.drop_constraint('contracts_commercial_user_id_fkey', 'contracts', type_='foreignkey')
    op.alter_column('contracts', 'commercial_user_id', new_column_name='sale_user_id')
    op.create_foreign_key(None, 'contracts', 'users', ['sale_user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('clients_sale_user_id_fkey', 'clients', type_='foreignkey')
    op.alter_column('clients', 'sale_user_id', new_column_name='commercial_user_id')
    op.create_foreign_key(None, 'clients', 'users', ['commercial_user_id'], ['id'])
    op.drop_constraint('contracts_sale_user_id_fkey', 'contracts', type_='foreignkey')
    op.alter_column('contracts', 'sale_user_id', new_column_name='commercial_user_id')
    op.create_foreign_key(None, 'contracts', 'users', ['commercial_user_id'], ['id'])
    # ### end Alembic commands ###
