"""empty message

Revision ID: e94c8a0b92d6
Revises: d3dae21e23f0
Create Date: 2023-10-23 23:36:09.619610

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from epic_events.models.user import User

# revision identifiers, used by Alembic.
revision: str = 'e94c8a0b92d6'
down_revision: Union[str, None] = 'd3dae21e23f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('UPDATE users SET role_id = 3 WHERE role_id IS NULL;')
    op.alter_column('users', 'role_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
